lib/hello_live_view_web/router.ex
defmodule HelloLiveViewWeb.Router do
  use HelloLiveViewWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HelloLiveViewWeb.Locale
    plug :put_root_layout, {HelloLiveViewWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloLiveViewWeb do
    pipe_through :browser

    get "/", PageController, :index
    live "/users/new", UserNew
    live "/users/:id/edit", UserEdit
    live "/users/:id", UserShow
    resources "/users", UserController, only: [:index]
    live "/limit", Limit
    live_dashboard "/dashboard", metrics: HelloLiveViewWeb.Telemetry
  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloLiveViewWeb do
  #   pipe_through :api
  # end
end

lib/hello_live_view_web/views/layout_view.ex
defmodule HelloLiveViewWeb.LayoutView do
  use HelloLiveViewWeb, :view
end

lib/hello_live_view_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= render @view_module, @view_template, assigns %>
</main>

lib/hello_live_view_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>HelloLiveView · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Hello LiveView</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="nav-content">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><%= link(gettext("Users"), to: Routes.user_path(@conn, :index), class: "nav-link") %></li>
              <li class="nav-item"><a class="nav-link" href="?locale=en">English</a></li>
              <li class="nav-item"><a class="nav-link" href="?locale=zh">中文</a></li>
            </ul>
          </div>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>