lib/hello_live_view_web/router.ex
defmodule HelloLiveViewWeb.Router do
  use HelloLiveViewWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HelloLiveViewWeb.Locale
    plug :put_root_layout, {HelloLiveViewWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloLiveViewWeb do
    pipe_through :browser

    get "/", PageController, :index
    live "/users/new", UserNew
    live "/users/:id/edit", UserEdit
    live "/users/:id", UserShow
    resources "/users", UserController, only: [:index]
    live "/limit", Limit
    live_dashboard "/dashboard", metrics: HelloLiveViewWeb.Telemetry
  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloLiveViewWeb do
  #   pipe_through :api
  # end
end

lib/hello_live_view/accounts/user.ex
defmodule HelloLiveView.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :email, :string
    field :password_digest, :string
    field :username, :string
    field :password, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:username, :email, :password])
    |> validate_required([:username, :email])
    |> validate_format(:email, ~r/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
    |> validate_length(:password, min: 8)
    |> put_password_hash()
    |> unique_constraint(:email)
    |> unique_constraint(:username)
  end

  @doc false
  def register_changeset(user, attrs) do
    changeset(user, attrs)
    |> validate_required([:password])
  end

  defp put_password_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} when is_binary(pass) ->
        put_change(changeset, :password_digest, Bcrypt.hash_pwd_salt(pass))

      _ ->
        changeset
    end
  end
end

lib/hello_live_view_web/controllers/user_controller.ex
defmodule HelloLiveViewWeb.UserController do
  use HelloLiveViewWeb, :controller

  def index(%{assigns: %{locale: locale}} = conn, _params) do
    live_render(conn, HelloLiveViewWeb.UserIndex, session: %{"locale" => locale})
  end
end

lib/hello_live_view_web/views/user_view.ex
defmodule HelloLiveViewWeb.UserView do
  use HelloLiveViewWeb, :view
end

lib/hello_live_view_web/templates/user/form.html.leex
<div class="row">
  <div class="col col-sm-6 offset-sm-3">
    <%= form_for @changeset, "#", [phx_change: "validate-user", phx_submit: "submit-user"], fn f -> %>
      <div class="form-group">
        <%= label f, :username %>
        <%= text_input f, :username, class: add_error_class(f, :username, "form-control") %>
        <%= error_tag f, :username %>
      </div>
      <div class="form-group">
        <%= label f, :email %>
        <%= text_input f, :email, class: add_error_class(f, :email, "form-control") %>
        <%= error_tag f, :email %>
      </div>

      <div class="form-group">
        <%= label f, :password %>
        <%= password_input f, :password, class: add_error_class(f, :password, "form-control") %>
        <%= error_tag f, :password %>
      </div>

      <%= submit "Submit", disabled: !@changeset.valid?, class: "btn btn-primary" %>
    <% end %>
    <%= if assigns[:number_of_users] do %>
      <%= if @number_of_users > 1 do %>
        <p><%= @number_of_users - 1 %> other user(s) editing</p>
      <% else %>
        <p>No other users are editing</p>
      <% end %>
    <% end %>
  </div>
</div>

lib/hello_live_view_web/templates/user/index.html.leex
<div class="row">
  <div class="col col-sm-6 offset-sm-3">
    <ul class="list-group list-group-flush mb-3" phx-update="append" id="users">
      <%= for user <- @users do %>
        <%= live_component @socket, HelloLiveViewWeb.UserRow, id: user.id %>
      <% end %>
    </ul>
    <%= link("Create user", to: Routes.live_path(@socket, HelloLiveViewWeb.UserNew), class: "btn btn-primary", phx_click: "show-modal", data_target: "#new-user", data_toggle: "modal") %>
  </div>
</div>

<%= if @open_modal do %>
  <div class="modal fade show" data-backdrop="static" tabindex="-1" role="dialog" id="new-user" aria-modal="true" style="display: block;">
<% else %>
  <div class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" id="new-user">
<% end %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" phx-click="close-modal">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @changeset, "#", [phx_change: "validate-user"], fn f -> %>
          <div class="form-group">
            <%= label f, :username %>
            <%= text_input f, :username, class: "form-control" %>
            <%= error_tag f, :username %>
          </div>
          <div class="form-group">
            <%= label f, :email %>
            <%= text_input f, :email, class: "form-control" %>
            <%= error_tag f, :email %>
          </div>

          <div class="form-group">
            <%= label f, :password %>
            <%= password_input f, :password, class: "form-control" %>
            <%= error_tag f, :password %>
          </div>

          <%= submit "Submit", disabled: !@changeset.valid?, class: "btn btn-primary", data_dismiss: "modal", phx_click: "submit-user" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

lib/hello_live_view_web/templates/user/show.html.leex
<div class="row">
  <div class="col col-sm-6 offset-sm-3">
    <table class="table">
      <thead>
        <tr>
          <th>Field:</th>
          <th>Data:</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Email:</td>
          <td><%= @user.email %>
        <tr>
        <tr>
          <td>Username:</td>
          <td><%= @user.username %>
        <tr>
      </tbody>
    </table>
  </div>
</div>